name    'hastexo-fetchfact'
version '0.0.1'
author 'hastexo'
license 'Apache License, Version 2.0'
summary 'Fetches facts with wget.'
description 'Fetches JSON, YAML or text data with wget, and makes it available as facts viafacter-dot-d.'
project_page 'https://github.com/fghaas/fetchfact'
dependency 'maestrodev/wget', '>= 1.0.0'
