name    'hastexo-fetchfact'
version '0.0.1'
author 'hastexo'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'
dependency 'maestrodev/wget', '>= 1.0.0'
